apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dnshortcut
rules:
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "watch", "list"]
- apiGroups: [""]
  resources: ["ingress"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["projectcontour.io"]
  resources: ["httpproxies"]
  verbs: ["get", "watch", "list"]